### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by T0ngChen** [T0ngChen/medRCT#1]
- [ ] handle continuous outcomes/continuous mediators/continuous intermediate confounders
- [ ] handle categorical exposure
- [ ] estimating the natural effect (without intermediate confounders)
- [ ] include the total effect & direct effect in the output
